# Generated by Django 5.2.17 on 2026-08-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrypool', '0002_add_blueprint_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('claimed', 'Claimed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('waiting_for_copies', 'Waiting for Copies')], default='open', max_length=20),
        ),
    ]
